

TURN_FULL_LEFT = 90
TURN_FULL_RIGHT = -90

TURN_HALF_LEFT = 45
TURN_HALF_RIGHT = -45

TURN_ONE_ONEHALF_LEFT = 135
TURN_ONO_ONEHALF_RIGHT = -135

LOOKING_FULL_UP = 90
LOOKING_FULL_DOWN = 270
LOOKING_FULL_RIGHT = 0
LOOKING_FULL_LEFT = 180

LOOKING_HALF_UP_HALF_RIGHT = 45
LOOKING_HALF_UP_HALF_LEFT = 135 
LOOKING_HALF_DOWN_HALF_RIGHT = 225
LOOKING_HALF_DOWN_HALF_LEFT = 315

SERVO_LOOK_LEFT = 90 # Servo Look Left
SERVO_LOOK_RIGHT = -90 # Servo Look Right